name: "Release"
on: [release]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
          components: clippy
    - run: cargo clippy --all-targets --all-features -- -D warnings
    - run: cargo build --verbose --release
    - uses: Shopify/upload-to-release@master
      with:
        name: frieren.exe
        path: target/release/frieren.exe
        content-type: text/plain
        repo-token: ${{ secrets.GITHUB_TOKEN }}
