name: Rust

on:
  push:
    branches: [ "rezero" ]
  pull_request:
    branches: [ "rezero" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
          components: clippy
    - run: cargo clippy --all-targets --all-features -- -D warnings
